# Welcome to Colab!

In [35]:
#découverte des valeurs manquantes
df.isnull().sum()

Age                                   1
BMI                                  27
Sex                                   2
Height                               26
Weight                                3
Length_of_Stay                        4
Management                            1
Severity                              1
Diagnosis_Presumptive                 2
Diagnosis                             2
Alvarado_Score                       52
Paedriatic_Appendicitis_Score        52
Appendix_on_US                        5
Appendix_Diameter                   284
Migratory_Pain                        9
Lower_Right_Abd_Pain                  8
Contralateral_Rebound_Tenderness     15
Coughing_Pain                        16
Nausea                                8
Loss_of_Appetite                     10
Body_Temperature                      7
WBC_Count                             6
Neutrophil_Percentage               103
Segmented_Neutrophils               728
Neutrophilia                         50
RBC_Count                            18
Hemoglobin                           18
RDW                                  26
Thrombocyte_Count                    18
Ketones_in_Urine                    200
RBC_in_Urine                        206
WBC_in_Urine                        199
CRP                                  11
Dysuria                              29
Stool                                17
Peritonitis                           9
Psoas_Sign                           37
Ipsilateral_Rebound_Tenderness      163
US_Performed                          4
US_Number                            22
Free_Fluids                          63
Appendix_Wall_Layers                564
Target_Sign                         644
Appendicolith                       713
Perfusion                           719
Perforation                         701
Surrounding_Tissue_Reaction         530
Appendicular_Abscess                697
Abscess_Location                    769
Pathological_Lymph_Nodes            579
Lymph_Nodes_Location                661
Bowel_Wall_Thickening               683
Conglomerate_of_Bowel_Loops         739
Ileus                               722
Coprostasis                         711
Meteorism                           642
Enteritis                           716
Gynecological_Findings              756
dtype: int64

In [44]:
df['Appendix_Diameter'].fillna(df['Appendix_Diameter'].median(),inplace=True)
df['Neutrophil_Percentage'].fillna(df['Neutrophil_Percentage'].median(),inplace=True)
df['Alvarado_Score'].fillna(df['Alvarado_Score'].median(),inplace=True)
df['Paedriatic_Appendicitis_Score'].fillna(df['Paedriatic_Appendicitis_Score'].median(),inplace=True)
df['BMI'].fillna(df['BMI'].median(),inplace=True)
df['Height'].fillna(df['Height'].median(),inplace=True)
df['RDW'].fillna(df['RDW'].median(),inplace=True)
df['US_Number'].fillna(df['US_Number'].median(),inplace=True)
df['Hemoglobin'].fillna(df['Hemoglobin'].median(),inplace=True)
df['Thrombocyte_Count'].fillna(df['Thrombocyte_Count'].median(),inplace=True)
df['RBC_Count'].fillna(df['RBC_Count'].median(),inplace=True)
df['CRP'].fillna(df['CRP'].median(),inplace=True)
df['Body_Temperature'].fillna(df['Body_Temperature'].median(),inplace=True)
df['WBC_Count'].fillna(df['WBC_Count'].median(),inplace=True)
df['Length_of_Stay'].fillna(df['Length_of_Stay'].median(),inplace=True)
df['Weight'].fillna(df['Weight'].median(),inplace=True)
df['Age'].fillna(df['Age'].median(),inplace=True)

/tmp/ipykernel_352/2642614083.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Appendix_Diameter'].fillna(df['Appendix_Diameter'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Neutrophil_Percentage'].fillna(df['Neutrophil_Percentage'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Alvarado_Score'].fillna(df['Alvarado_Score'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Paedriatic_Appendicitis_Score'].fillna(df['Paedriatic_Appendicitis_Score'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BMI'].fillna(df['BMI'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Height'].fillna(df['Height'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RDW'].fillna(df['RDW'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['US_Number'].fillna(df['US_Number'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Hemoglobin'].fillna(df['Hemoglobin'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Thrombocyte_Count'].fillna(df['Thrombocyte_Count'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RBC_Count'].fillna(df['RBC_Count'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CRP'].fillna(df['CRP'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Body_Temperature'].fillna(df['Body_Temperature'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['WBC_Count'].fillna(df['WBC_Count'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Length_of_Stay'].fillna(df['Length_of_Stay'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Weight'].fillna(df['Weight'].median(),inplace=True)
/tmp/ipykernel_352/2642614083.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)

In [41]:
df.head(10)

,Age,BMI,Sex,Height,Weight,Length_of_Stay,Management,Severity,Diagnosis_Presumptive,Diagnosis,...,Abscess_Location,Pathological_Lymph_Nodes,Lymph_Nodes_Location,Bowel_Wall_Thickening,Conglomerate_of_Bowel_Loops,Ileus,Coprostasis,Meteorism,Enteritis,Gynecological_Findings
0,12.68,16.9,female,148.0,37.0,3.0,conservative,uncomplicated,appendicitis,appendicitis,...,NaN,yes,reUB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14.10,31.9,male,147.0,69.5,2.0,conservative,uncomplicated,appendicitis,no appendicitis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
2,14.14,23.3,female,163.0,62.0,4.0,conservative,uncomplicated,appendicitis,no appendicitis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,NaN
3,16.37,20.6,female,165.0,56.0,3.0,conservative,uncomplicated,appendicitis,no appendicitis,...,NaN,yes,reUB,NaN,NaN,NaN,NaN,NaN,yes,NaN
4,11.08,16.9,female,163.0,45.0,3.0,conservative,uncomplicated,appendicitis,appendicitis,...,NaN,yes,reUB,NaN,NaN,NaN,NaN,NaN,yes,NaN
5,11.05,30.7,male,121.0,45.0,3.0,conservative,uncomplicated,appendicitis,no appendicitis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,8.98,19.4,female,140.0,38.5,3.0,conservative,uncomplicated,appendicitis,no appendicitis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7.06,NaN,female,NaN,21.5,2.0,conservative,uncomplicated,appendicitis,no appendicitis,...,NaN,yes,re UB,no,NaN,NaN,NaN,NaN,NaN,NaN
8,7.90,15.7,male,131.0,26.7,3.0,conservative,uncomplicated,appendicitis,no appendicitis,...,NaN,yes,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
9,14.34,14.9,male,174.0,45.5,3.0,conservative,uncomplicated,appendicitis,appendicitis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
print(df['Appendix_Diameter'])

0       7.1
1       7.5
2       7.5
3       7.5
4       7.0
       ...
777     7.5
778     7.5
779     7.5
780    14.0
781     8.0
Name: Appendix_Diameter, Length: 782, dtype: float64

In [45]:
df.isnull().sum()

Age                                   0
BMI                                   0
Sex                                   2
Height                                0
Weight                                0
Length_of_Stay                        0
Management                            1
Severity                              1
Diagnosis_Presumptive                 2
Diagnosis                             2
Alvarado_Score                        0
Paedriatic_Appendicitis_Score         0
Appendix_on_US                        5
Appendix_Diameter                     0
Migratory_Pain                        9
Lower_Right_Abd_Pain                  8
Contralateral_Rebound_Tenderness     15
Coughing_Pain                        16
Nausea                                8
Loss_of_Appetite                     10
Body_Temperature                      0
WBC_Count                             0
Neutrophil_Percentage                 0
Segmented_Neutrophils               728
Neutrophilia                         50
RBC_Count                             0
Hemoglobin                            0
RDW                                   0
Thrombocyte_Count                     0
Ketones_in_Urine                    200
RBC_in_Urine                        206
WBC_in_Urine                        199
CRP                                   0
Dysuria                              29
Stool                                17
Peritonitis                           9
Psoas_Sign                           37
Ipsilateral_Rebound_Tenderness      163
US_Performed                          4
US_Number                             0
Free_Fluids                          63
Appendix_Wall_Layers                564
Target_Sign                         644
Appendicolith                       713
Perfusion                           719
Perforation                         701
Surrounding_Tissue_Reaction         530
Appendicular_Abscess                697
Abscess_Location                    769
Pathological_Lymph_Nodes            579
Lymph_Nodes_Location                661
Bowel_Wall_Thickening               683
Conglomerate_of_Bowel_Loops         739
Ileus                               722
Coprostasis                         711
Meteorism                           642
Enteritis                           716
Gynecological_Findings              756
dtype: int64

In [49]:
colonnes_faibles_cat = ['RBC_in_Urine','Ketones_in_Urine','WBC_in_Urine','Ipsilateral_Rebound_Tenderness'
    'Sex', 'Diagnosis', 'Seveity', 'Management', 'Neutrophilia',
    'Migratory_Pain', 'Lower_Right_Abd_Pain', 'Contralateral_Rebound_Tenderness',
    'Coughing_Pain', 'Nausea', 'Loss_of_Appetite', 'Dysuria',
    'Stool', 'Peritonitis', 'Psoas_Sign', 'Appendix_on_US',
    'US_Performed', 'Free_Fluids','Diagnosis_Presumptive']
    # Variables catégorielles → mode
for col in colonnes_faibles_cat:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].mode()[0])

In [50]:
df.isnull().sum()

Age                                   0
BMI                                   0
Sex                                   0
Height                                0
Weight                                0
Length_of_Stay                        0
Management                            0
Severity                              0
Diagnosis_Presumptive                 0
Diagnosis                             0
Alvarado_Score                        0
Paedriatic_Appendicitis_Score         0
Appendix_on_US                        0
Appendix_Diameter                     0
Migratory_Pain                        0
Lower_Right_Abd_Pain                  0
Contralateral_Rebound_Tenderness      0
Coughing_Pain                         0
Nausea                                0
Loss_of_Appetite                      0
Body_Temperature                      0
WBC_Count                             0
Neutrophil_Percentage                 0
Segmented_Neutrophils               728
Neutrophilia                          0
RBC_Count                             0
Hemoglobin                            0
RDW                                   0
Thrombocyte_Count                     0
Ketones_in_Urine                      0
RBC_in_Urine                          0
WBC_in_Urine                          0
CRP                                   0
Dysuria                               0
Stool                                 0
Peritonitis                           0
Psoas_Sign                            0
Ipsilateral_Rebound_Tenderness      163
US_Performed                          0
US_Number                             0
Free_Fluids                           0
Appendix_Wall_Layers                564
Target_Sign                         644
Appendicolith                       713
Perfusion                           719
Perforation                         701
Surrounding_Tissue_Reaction         530
Appendicular_Abscess                697
Abscess_Location                    769
Pathological_Lymph_Nodes            579
Lymph_Nodes_Location                661
Bowel_Wall_Thickening               683
Conglomerate_of_Bowel_Loops         739
Ileus                               722
Coprostasis                         711
Meteorism                           642
Enteritis                           716
Gynecological_Findings              756
dtype: int64

In [51]:
colonnes_critiques = [
    'Abscess_Location', 'Gynecological_Findings', 'Conglomerate_of_Bowel_Loops',
    'Segmented_Neutrophils', 'Ileus', 'Perfusion', 'Enteritis', 'Appendicolith',
    'Coprostasis', 'Perforation', 'Appendicular_Abscess', 'Bowel_Wall_Thickening',
    'Lymph_Nodes_Location', 'Target_Sign', 'Meteorism', 'Pathological_Lymph_Nodes',
    'Appendix_Wall_Layers', 'Surrounding_Tissue_Reaction'
]

# Convertir en binaire : 1 si valeur présente, 0 si manquant
for col in colonnes_critiques:
    df[col] = df[col].notna().astype(int)

In [52]:
df.isnull().sum()

Age                                   0
BMI                                   0
Sex                                   0
Height                                0
Weight                                0
Length_of_Stay                        0
Management                            0
Severity                              0
Diagnosis_Presumptive                 0
Diagnosis                             0
Alvarado_Score                        0
Paedriatic_Appendicitis_Score         0
Appendix_on_US                        0
Appendix_Diameter                     0
Migratory_Pain                        0
Lower_Right_Abd_Pain                  0
Contralateral_Rebound_Tenderness      0
Coughing_Pain                         0
Nausea                                0
Loss_of_Appetite                      0
Body_Temperature                      0
WBC_Count                             0
Neutrophil_Percentage                 0
Segmented_Neutrophils                 0
Neutrophilia                          0
RBC_Count                             0
Hemoglobin                            0
RDW                                   0
Thrombocyte_Count                     0
Ketones_in_Urine                      0
RBC_in_Urine                          0
WBC_in_Urine                          0
CRP                                   0
Dysuria                               0
Stool                                 0
Peritonitis                           0
Psoas_Sign                            0
Ipsilateral_Rebound_Tenderness      163
US_Performed                          0
US_Number                             0
Free_Fluids                           0
Appendix_Wall_Layers                  0
Target_Sign                           0
Appendicolith                         0
Perfusion                             0
Perforation                           0
Surrounding_Tissue_Reaction           0
Appendicular_Abscess                  0
Abscess_Location                      0
Pathological_Lymph_Nodes              0
Lymph_Nodes_Location                  0
Bowel_Wall_Thickening                 0
Conglomerate_of_Bowel_Loops           0
Ileus                                 0
Coprostasis                           0
Meteorism                             0
Enteritis                             0
Gynecological_Findings                0
dtype: int64

In [5]:
#Détection par IQR
colonnes_numeriques = ['Age', 'BMI', 'CRP', 'WBC_Count', 'Hemoglobin', 'Ipsilateral_Rebound_Tenderness',
                        'Body_Temperature', 'RDW', 'Appendix_Diameter',
                        'Alvarado_Score', 'Paedriatic_Appendicitis_Score',
                        'Length_of_Stay', 'Weight', 'Height', 'RBC_Count',
                        'Thrombocyte_Count', 'Neutrophil_Percentage']

for col in colonnes_numeriques:
    s = df[col].dropna()
    Q1, Q3 = s.quantile(0.25), s.quantile(0.75)
    IQR = Q3 - Q1
    bb, bh = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    n = ((s < bb) | (s > bh)).sum()
    print(f'{col}: {n} outliers | bornes=[{bb:.2f}, {bh:.2f}]')

#Détection par Z-scores
for col in colonnes_numeriques:
    s = df[col].dropna()
    z = np.abs(stats.zscore(s))
    print(f'{col}: {(z > 3).sum()} outliers (z>3)')

#suppression des valeurs biologiques impossibles
df = df[df['Body_Temperature'] > 34]
df = df[df['Hemoglobin'] <= 20]
df = df[df['RDW'] <= 30]
df = df[df['RBC_Count'] <= 8]

#Winnorisation
colonnes_winsor = ['BMI', 'WBC_Count', 'Length_of_Stay',
                   'Thrombocyte_Count', 'Appendix_Diameter']

for col in colonnes_winsor:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    borne_basse = Q1 - 1.5 * IQR
    borne_haute = Q3 + 1.5 * IQR
    df[col] = df[col].clip(lower=borne_basse, upper=borne_haute)

#Log-transformation de CRP
df['CRP_log'] = np.log1p(df['CRP'])

Age: 5 outliers | bornes=[1.85, 21.45]
BMI: 23 outliers | bornes=[7.54, 29.36]
CRP: 85 outliers | bornes=[-47.00, 81.00]
WBC_Count: 6 outliers | bornes=[-3.80, 28.20]
Hemoglobin: 16 outliers | bornes=[10.50, 16.10]

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [10]:
import pandas as pd

# Chargement de votre fichier
# Assurez-vous que le chemin est correct
df = df=pd.read_excel("/content/app_data_final.xlsx")

# 1. Analyse initiale des lignes vides sur la cible
lignes_vides_diagnostic = df['Diagnosis'].isnull().sum()
print(f"Nombre de lignes avec 'Diagnosis' manquant avant suppression : {lignes_vides_diagnostic}")

# 2. Suppression ciblée (uniquement sur la colonne 'Diagnosis')
df_clean = df.dropna(subset=['Diagnosis']).copy()

# 3. Vérification
print(f"Nombre de lignes restantes : {len(df_clean)}")
print("Nettoyage effectué avec succès.")

Nombre de lignes avec 'Diagnosis' manquant avant suppression : 0
Nombre de lignes restantes : 776
Nettoyage effectué avec succès.